version: '3.0'

networks:
  myNetwork:
    driver: bridge

services:
  client:
    depends_on:
      - server
    container_name: learning-graphql-client
    build:
      context: ./client
      args:
        - SERVER_PROXY_PASS=location /graphql { proxy_pass http://learning-graphql-server:4000/graphql; }
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - myNetwork

  server:
    container_name: learning-graphql-server
    build: ./server
    restart: always
    environment:
      - CLIENT_URL=${CLIENT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - SERVER_URL=${SERVER_URL}
    ports:
      - "${PORT}:4000"
    networks:
      - myNetwork


## Build and run locally
## Before run the command below the environment variables must be provided
# docker-compose up
