version: '3.0'

networks:
  myNetwork:
    driver: bridge

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

    container_name: server.dev
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - myNetwork
    volumes:
      - ./server:/usr/app
    restart: always

  database:
    image: postgres:12

    container_name: postgres.dev
    env_file:
      - ./.env
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - myNetwork
    volumes:
      - ${PGDBPATH}:/var/lib/postgresql/data
    restart: always
