version: '3.0'

networks:
  mynetwork:
    driver: bridge

services:
  server:
    image: learning-graphql-server:latest

    container_name: learning-graphql-server
    env_file:
      - ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - mynetwork
    restart: always


  client:
    image: learning-graphql-client:latest

    env_file:
      - ./.env
    container_name: learning-graphql-client
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - mynetwork
    restart: always
