version: '3.0'

networks:
  myNetwork:
    driver: bridge

services:
  database:
    image: postgres:11

    container_name: postgres.dev
    env_file:
      - ./.env
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - myNetwork
    volumes:
      - ${POSTGRES_HOSTDATA}:/var/lib/postgresql/data
    restart: always


  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

    container_name: server.dev
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - myNetwork
    volumes:
      - ./server/src:/usr/app/src
      - ./server/tsconfig.json:/usr/app/tsconfig.json
    restart: always
