version: '3.0'

networks:
  myNetwork:
    driver: bridge

services:
  client:
    build:
      context: ./client
      args:
        - SERVER_PROXY_PASS=location /graphql { proxy_pass http://learning-graphql-server:${SERVER_PORT}/graphql; }

    container_name: learning-graphql-client
    depends_on:
      - server
    env_file:
      - ./.env
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - myNetwork
    restart: always

  server:
    build: ./server

    container_name: learning-graphql-server
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - myNetwork
    restart: always

  database:
    image: postgres:12

    container_name: postgres
    env_file:
      - ./.env
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - myNetwork
    volumes:
      - ${PGDBPATH}:/var/lib/postgresql/data
    restart: always
