version: '3.0'

networks:
  myNetwork:
    driver: bridge

services:
  # client:
  #   depends_on:
  #     - server
  #   container_name: learning-graphql-client
  #   build:
  #     context: ./client
  #     args:
  #       - SERVER_PROXY_PASS=location /graphql { proxy_pass http://learning-graphql-server:4000/graphql; }
  #   ports:
  #     - "${CLIENT_PORT}:80"
  #   networks:
  #     - myNetwork

  # server:
  #   container_name: learning-graphql-server
  #   build: ./server
  #   restart: always
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "${PORT}:4000"
  #   networks:
  #     - myNetwork

  database:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - myNetwork
    volumes:
      - /Users/belchior/postgres/data:/usr/lib/postgres/data

## Build and run locally
## Before run the command below the environment variables must be provided
# docker-compose up
