version: "3.7"

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:
  database:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db
    networks:
      - mynetwork

  server:
    depends_on:
      - database
    build: .
    container_name: server
    command: ["npm", "run", "start:ts"]
    restart: always
    environment:
      - DEBUG=${DEBUG}
      - NODE_ENV={NODE_ENV}
      - DATABASE_URL=mongodb://database:27017/learning-graphql
    ports:
      - "${PORT}:4000"
    volumes:
      - ".:/usr/app"
    networks:
      - mynetwork
